### ISSUE TITLE
Karma single/auto run..

### ISSUE THREAD

**Issue by jjcastano** [serenity-frontstack/angular-basic#6]
Whenever you use _karma:single-run_ or _karma:auto-run_, they call _runTests_ function wich override the run mode to be always _singleRun_

Your code:
```
function runTests (singleRun,done) {
  var singleRun = true;
  ...
```

**Comment by josemanuelbd** [comment]
Thank you for your feedback @jjcastano .We are fixed this issue in version 1.2.5. Be careful when you try to execute commands in next times, because we are changed our task by npm scripts. Check out our README.md file to view how to run the commands of angular basic. Thank you once again for your proactive work ;)
